/**
 * Cloudflare Worker: Analyze Image with Gemini AI
 * 
 * This worker receives base64-encoded images from the mobile app,
 * sends them to Google Gemini API for analysis, and returns structured
 * classification data including title, description, tags, and TTS script.
 * 
 * Endpoint: POST /api/analyze-image
 * 
 * Request Body:
 * {
 *   imageBase64: string,  // Base64-encoded image data
 *   mimeType: string      // Image MIME type (e.g., 'image/jpeg')
 * }
 * 
 * Response:
 * {
 *   classification: string,
 *   title: string,
 *   description?: string,
 *   script?: string,
 *   tags?: string[],
 *   duration?: number,
 *   place_name?: string,
 *   place_address?: string
 * }
 * 
 * Environment Variables Required:
 * - GEMINI_API_KEY: Google Gemini API key (server-side only)
 */

import { Env, ClassificationResult, ErrorResponse } from './types';

/**
 * Parse Gemini API response and extract structured classification data
 */
function parseGeminiResponse(geminiText: string): ClassificationResult {
  try {
    // Gemini returns JSON-like text, parse it
    const jsonMatch = geminiText.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        classification: parsed.classification || 'other',
        title: parsed.title || 'Untitled',
        description: parsed.description,
        script: parsed.script,
        tags: parsed.tags || [],
        duration: parsed.duration,
        place_name: parsed.place_name,
        place_address: parsed.place_address,
      };
    }
    throw new Error('Failed to parse Gemini response');
  } catch (error) {
    // Fallback if parsing fails
    return {
      classification: 'other',
      title: 'Image',
      description: geminiText.substring(0, 200),
      tags: [],
    };
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Only accept POST requests
    if (request.method !== 'POST') {
      return new Response(
        JSON.stringify({ error: 'Method not allowed' } as ErrorResponse),
        { 
          status: 405,
          headers: { 'Content-Type': 'application/json' }
        }
      );
    }

    // Enable CORS for mobile app
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Content-Type': 'application/json',
    };

    // Handle preflight requests
    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    try {
      const { imageBase64, mimeType } = await request.json() as {
        imageBase64: string;
        mimeType: string;
      };

      if (!imageBase64 || !mimeType) {
        return new Response(
          JSON.stringify({ 
            error: 'Missing required fields',
            details: 'imageBase64 and mimeType are required'
          } as ErrorResponse),
          { status: 400, headers: corsHeaders }
        );
      }

      // Construct prompt for Gemini
      const analysisPrompt = `Analyze this image and classify it into one of these categories: article, video, recipe, product, event, place, idea, or other.

Return a JSON object with the following structure:
{
  "classification": "category",
  "title": "brief title",
  "description": "detailed description (2-3 sentences)",
  "script": "natural spoken summary for text-to-speech (1-2 sentences)",
  "tags": ["tag1", "tag2", "tag3"],
  "duration": estimated_minutes_to_review,
  "place_name": "if it's a place/location",
  "place_address": "if it's a place/location"
}

Be concise and accurate. The script should sound natural when spoken aloud.`;

      // Call Gemini API
      const geminiResponse = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${env.GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              parts: [
                { 
                  inlineData: { 
                    data: imageBase64, 
                    mimeType 
                  } 
                },
                { text: analysisPrompt }
              ]
            }]
          })
        }
      );

      if (!geminiResponse.ok) {
        const errorText = await geminiResponse.text();
        throw new Error(`Gemini API error: ${geminiResponse.status} - ${errorText}`);
      }

      const geminiData = await geminiResponse.json() as any;
      
      // Extract text from Gemini response
      const generatedText = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!generatedText) {
        throw new Error('No text generated by Gemini');
      }

      // Parse and structure the response
      const result = parseGeminiResponse(generatedText);

      return new Response(JSON.stringify(result), {
        headers: corsHeaders
      });

    } catch (error) {
      console.error('Image analysis error:', error);
      
      return new Response(
        JSON.stringify({ 
          error: 'Failed to analyze image',
          details: error instanceof Error ? error.message : 'Unknown error'
        } as ErrorResponse),
        {
          status: 500,
          headers: corsHeaders
        }
      );
    }
  }
};

