/**
 * Cloudflare Worker: Suggest Schedule Time with Gemini AI
 * 
 * This worker uses Google Gemini API to suggest optimal time slots
 * for reviewing content based on its classification, title, and estimated duration.
 * 
 * Endpoint: POST /api/suggest-schedule
 * 
 * Request Body:
 * {
 *   title: string,
 *   classification: string,
 *   description?: string,
 *   duration?: number
 * }
 * 
 * Response:
 * {
 *   date: string,      // ISO date string
 *   time: string,      // Time in HH:MM format
 *   reason: string     // Explanation for the suggestion
 * }
 * 
 * Environment Variables Required:
 * - GEMINI_API_KEY: Google Gemini API key (server-side only)
 */

import { Env, ScheduleSuggestion, ErrorResponse } from './types';

/**
 * Parse Gemini response to extract schedule suggestion
 */
function parseScheduleSuggestion(geminiText: string): ScheduleSuggestion {
  try {
    const jsonMatch = geminiText.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        date: parsed.date || new Date().toISOString().split('T')[0],
        time: parsed.time || '09:00',
        reason: parsed.reason || 'General suggestion',
      };
    }
    throw new Error('Failed to parse Gemini response');
  } catch (error) {
    // Default to tomorrow morning
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    return {
      date: tomorrow.toISOString().split('T')[0],
      time: '09:00',
      reason: 'Default suggestion for tomorrow morning',
    };
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method !== 'POST') {
      return new Response(
        JSON.stringify({ error: 'Method not allowed' } as ErrorResponse),
        { 
          status: 405,
          headers: { 'Content-Type': 'application/json' }
        }
      );
    }

    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Content-Type': 'application/json',
    };

    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    try {
      const { title, classification, description, duration } = await request.json() as {
        title: string;
        classification: string;
        description?: string;
        duration?: number;
      };

      if (!title || !classification) {
        return new Response(
          JSON.stringify({ 
            error: 'Missing required fields',
            details: 'title and classification are required'
          } as ErrorResponse),
          { status: 400, headers: corsHeaders }
        );
      }

      // Get current date/time
      const now = new Date();
      const currentDate = now.toISOString().split('T')[0];
      const currentTime = now.toTimeString().split(' ')[0].substring(0, 5);

      // Construct prompt for Gemini
      const schedulePrompt = `Suggest the best time to review this content:

Title: ${title}
Type: ${classification}
${description ? `Description: ${description}` : ''}
${duration ? `Estimated duration: ${duration} minutes` : ''}

Current date: ${currentDate}
Current time: ${currentTime}

Consider:
- Articles/recipes: morning or evening (focused reading time)
- Videos: evening or weekend (leisure time)
- Events: at least 1 day before the event
- Products: when user might be shopping (afternoon/evening)
- Ideas: morning (creative time)

Return a JSON object:
{
  "date": "YYYY-MM-DD",
  "time": "HH:MM",
  "reason": "brief explanation (1 sentence)"
}

Suggest a date within the next 7 days.`;

      // Call Gemini API
      const geminiResponse = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${env.GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              parts: [{ text: schedulePrompt }]
            }]
          })
        }
      );

      if (!geminiResponse.ok) {
        const errorText = await geminiResponse.text();
        throw new Error(`Gemini API error: ${geminiResponse.status} - ${errorText}`);
      }

      const geminiData = await geminiResponse.json() as any;
      const generatedText = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (!generatedText) {
        throw new Error('No text generated by Gemini');
      }

      const suggestion = parseScheduleSuggestion(generatedText);

      return new Response(JSON.stringify(suggestion), {
        headers: corsHeaders
      });

    } catch (error) {
      console.error('Schedule suggestion error:', error);
      
      return new Response(
        JSON.stringify({ 
          error: 'Failed to suggest schedule',
          details: error instanceof Error ? error.message : 'Unknown error'
        } as ErrorResponse),
        {
          status: 500,
          headers: corsHeaders
        }
      );
    }
  }
};

